version: "3.8"
services:
    server:
        env_file:
            - .env
        container_name: server
        build:
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            - db
        volumes:
            - .:/usr/src/app

    db:
        container_name: db
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - data:/data/db
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}

volumes:
    data: {}
